logging:
  level: INFO
  loggers:
    org.softwire.training: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: Waegooz2

  # nullNamePatternMatchesAll=true because https://liquibase.jira.com/browse/CORE-2723
  url: jdbc:mysql://webdev-db.c6lhbh6lfabc.eu-west-1.rds.amazonaws.com:3306/webdev?verifyServerCertificate=false&useSSL=true&nullNamePatternMatchesAll=true&serverTimezone=UTC

  properties:
    charSet: UTF-8

  maxWaitForConnection: 1s
  validationQuery: "/* PhotoCompetition Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute

rawImages:
  s3Bucket: webdev-webdevs3bucket-16ufyhtxjw06m

adminPassword: Change Me!
moderatorPassword: moderator